[tool.black]
line-length = 120
target-version = ["py36", "py37", "py38", "py39", "py310"]
experimental-string-processing = true
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
  |Jenkinfile
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_local_folder = ["pdf-service"]
