version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: docker.ops.iszn.cz/upstream/postgres/postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=pdf
      - POSTGRES_PASSWORD=pdf
      - POSTGRES_DB=pdf
      - PGPORT=9432
  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    expose:
      - 5672

volumes:
  postgres-data:
