version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: docker.ops.iszn.cz/upstream/postgres/postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=pdf
      - POSTGRES_PASSWORD=pdf
      - POSTGRES_DB=pdf
      - PGPORT=9432
  rabbitmq:
    image: docker.ops.iszn.cz/upstream/bitnami/rabbitmq:latest
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

    networks:
      - rabbitmq_net
volumes:
  postgres-data:

networks:
  rabbitmq_net:
    driver: bridge
